version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: sgl:release-v1
    container_name: release-v1
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ./app:/usr/src/app/app
      - ./config:/usr/src/app/config
      - ./db/production:/usr/src/app/db/production   
    extra_hosts:
      - "bbb.pipitacademy.com:10.10.0.79"
# When using sqlite3 as the database
#    volumes:
#      - ./db/production:/usr/src/app/db/production
   
# When using postgresql as the database
#    links:
#      - db
#  db:
#    image: postgres:9.5
#    restart: on-failure
#    ports:
#      - 127.0.0.1:5432:5432
#    volumes:
#      - ./db/production:/var/lib/postgresql/data
#    environment:
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGUSER=postgres
#      - PGPASSWORD=password
